# Generated by Django 4.0.6 on 2022-08-05 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='logo_url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='sector',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='website',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='ticker',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('count', models.BigIntegerField()),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_app.enterprise')),
            ],
        ),
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_app.enterprise')),
            ],
        ),
    ]
