# Generated by Django 4.0.6 on 2022-08-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_app', '0003_alter_dividend_price_alter_share_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='share',
            name='count',
        ),
        migrations.AddField(
            model_name='enterprise',
            name='share_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='share',
            name='volume',
            field=models.IntegerField(default=0),
        ),
    ]
